### ISSUE TITLE
"goal not found" error with pq_astar

### ISSUE THREAD

**Issue by HareshKarnan** [omron-sinicx/neural-astar#11]
I have a 416x416 empty map (all zeros), and I have appropriate start and goal maps. When using pq_astar, it throws an output saying "goal not found" and returns empty histories and paths tensors with all zeros.

**Comment by yonetaniryo** [comment]
Thank you for reporting! Actually I didn’t assume empty maps to be given as inputs, but they should be all-ones rather than all-zeros (in my implementation `1` means passable).

https://github.com/omron-sinicx/neural-astar/blob/6d88e7ca4c00447862da4650e5b339489371e3c4/src/neural_astar/planner/pq_astar.py#L137

**Comment by HareshKarnan** [comment]
Thanks for the quick response! My issue has been resolved. :)

**Comment by yonetaniryo** [comment]
This may not be very intuitive, indeed. Will clarify it in the next update. Thanks!

**Comment by HareshKarnan** [comment]
https://github.com/omron-sinicx/neural-astar/blob/6d88e7ca4c00447862da4650e5b339489371e3c4/src/neural_astar/planner/astar.py#L93

this line or the next needs to be changed
