### ISSUE TITLE
Some confusions

### ISSUE THREAD

**Issue by qzxxzq** [omron-sinicx/neural-astar#19]
Hi, I have some confusion about this amazing work.
1. I would like to inquire about the MP Dataset results described in the article. I noticed that you separated the environment groups for training and testing. How were the final results calculated after integrating these groups?
2. Regarding the ground-truth, I was wondering why Dijkstra's algorithm was used instead of standard A*. Additionally, when I utilized your source code, I found that the ground-truth (opt_traj) generated by Dijkstra's algorithm may not always be optimal. Could you offer any insight on this matter?

![example](https://user-images.githubusercontent.com/56544799/233529134-bc17efd0-2887-421a-812c-dec37072286d.png)

**Comment by yonetaniryo** [comment]
Hi, thank you for the question!

1. The results obtained for each environment group separately are just averaged to obtain the final result, if I remembered it correctly.
2. We chose to use dijkstra just because we want to compute shortest paths from all pixels to a single goal efficiently. In the attached result, the dijkstra path is actually treated as optimal because we give uniform cost to all of the eight directions  (ie vertical, horizontal, and diagonal steps are all equal in terms of cost) by following previous work.
